"""Add verschiedene PUMA field to Laptop model

Revision ID: 861535f3373c
Revises: 3a2c6976dea6
Create Date: 2024-08-21 10:42:28.857940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861535f3373c'
down_revision = '3a2c6976dea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puma_ice', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_ice_lizenz_datum', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_e_motor', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_e_motor_lizenz_datum', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_batterie', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_batterie_lizenz_datum', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('puma_batterie_lizenz_datum')
        batch_op.drop_column('puma_batterie')
        batch_op.drop_column('puma_e_motor_lizenz_datum')
        batch_op.drop_column('puma_e_motor')
        batch_op.drop_column('puma_ice_lizenz_datum')
        batch_op.drop_column('puma_ice')

    # ### end Alembic commands ###
