"""change laptop model information

Revision ID: b73335900b6c
Revises: 861535f3373c
Create Date: 2024-08-30 15:41:44.650722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73335900b6c'
down_revision = '861535f3373c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puma_ice_version', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_e_motor_version', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_batterie_version', sa.String(length=150), nullable=True))
        batch_op.drop_column('puma_ice')
        batch_op.drop_column('puma_e_motor')
        batch_op.drop_column('puma_batterie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puma_batterie', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_e_motor', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_ice', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('puma_batterie_version')
        batch_op.drop_column('puma_e_motor_version')
        batch_op.drop_column('puma_ice_version')

    # ### end Alembic commands ###
