"""change laptop model information

Revision ID: d307be3e7d31
Revises: b73335900b6c
Create Date: 2024-08-30 16:14:33.061751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd307be3e7d31'
down_revision = 'b73335900b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puma_eMotor_version', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_eMotor_lizenz_datum', sa.String(length=150), nullable=True))
        batch_op.drop_column('puma_e_motor_version')
        batch_op.drop_column('puma_e_motor_lizenz_datum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puma_e_motor_lizenz_datum', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_e_motor_version', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('puma_eMotor_lizenz_datum')
        batch_op.drop_column('puma_eMotor_version')

    # ### end Alembic commands ###
