"""Sync migrations with production database

Revision ID: e214476ba2ab
Revises: d307be3e7d31
Create Date: 2024-09-09 15:36:23.005063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e214476ba2ab'
down_revision = 'd307be3e7d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo')
    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puma_ice_version', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_ice_lizenz_datum', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_eMotor_version', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_eMotor_lizenz_datum', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_batterie_version', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('puma_batterie_lizenz_datum', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('puma_batterie_lizenz_datum')
        batch_op.drop_column('puma_batterie_version')
        batch_op.drop_column('puma_eMotor_lizenz_datum')
        batch_op.drop_column('puma_eMotor_version')
        batch_op.drop_column('puma_ice_lizenz_datum')
        batch_op.drop_column('puma_ice_version')

    op.create_table('demo',
    sa.Column('ID', sa.INTEGER(), nullable=True),
    sa.Column('Name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Hint', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
