"""Add customer and location column into booking model

Revision ID: e45a9714e7ab
Revises: d307be3e7d31
Create Date: 2024-09-10 14:06:47.164776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45a9714e7ab'
down_revision = 'd307be3e7d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('customer')

    # ### end Alembic commands ###
